### ISSUE TITLE
💡 SvForm cleaning associated stores

### ISSUE THREAD

**Issue by Ca10San** [ringeringeraja/savitri#7]
I've built a view with 2 stacked SvBox, both of them renders a collection inside SvTable but buton only one of them is associated to another collection. 

![image](https://user-images.githubusercontent.com/15050225/186528450-34c9f6be-e3cf-4267-8046-3deb8f250445.png)

When an SvForm renders the associated collection, the "items" entry is cleaned

![image](https://user-images.githubusercontent.com/15050225/186528614-249da32f-8a43-4943-bf70-5a832782c2ba.png)

Obs: The SvForm behavior triggers some 'clearItems' function

![image](https://user-images.githubusercontent.com/15050225/186529553-8926c114-e604-4670-a3b4-74f25a505609.png)

This triggers comes from SvForm internals (SvSearch component)

![image](https://user-images.githubusercontent.com/15050225/186529927-4def2474-c149-4a03-a641-fb0f5e0d4add.png)

**Comment by Ca10San** [comment]
Despite this, it's something there's a caveat that can be used to avoid major problems in this specific case:

Calling a ".getAll()" on the affected store when the SvForm is unmounted or when the modal is going to be invisible.

But in other situations it can escalate to something problematic

**Comment by ringeringeraja** [comment]
Corrigido.
